### ISSUE TITLE
sds-webapp is deprecated, use sensitive-ws

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/avsb#83]
Current usage https://github.com/AtlasOfLivingAustralia/avsb/blob/main/src/api/sources/sds.ts

Changes:

`/sds-webapp/ws/{scientificName}`
- The replacement is `/sensitive/api/isSensitive?scientificName={scientificName}` or `/sensitive/api/isSensitive?taxonId={taxonId}`, returning plain text `true` or `false`. 
- The additional information `instances` is only available by finding it in the large response of `/sensitive/ws/species`.

`/sds-webapp/ws/{scientificName}/location/...`
- The replacement is `/sensitive/api/report?taxonId={taxonId}&stateProvince={stateProvince}&country={country}` e.g. `/sensitive/api/report?taxonId=https://id.biodiversity.org.au/taxon/apni/51399466&stateProvince=SA&country=AUS`.
- `scientificName={scientificName}` can be used instead of `taxonId={taxonId}`.
- The response does contain matched `instances`.

`/sds-webapp/ws/{scientificName}/location/.../date/...`
- No replacement available.

**Comment by jack-brinkman** [comment]
Fixed in #90
